const objectUrls = {
    DOOR_OPEN: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/K9QBG4Fdi13x6cl9pI2Vm5",
    DOOR_CLOSED: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/iYCzMZcwACa6lNibxvx7i8",
    SMALL_DOOR_OPEN: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/ZpGQqmkpBqPw3xrFok2fn5",
    SMALL_DOOR_CLOSED: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/ctLUdJ6GyNyIGHL0fqT1xE",
    VERTICAL_DOOR_OPEN: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/KshoQYjHGTD1WiniPG2xtf",
    VERTICAL_DOOR_CLOSED: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/JMQ21pHgUaK9GrZZhWJsYh",
    SMALL_VERTICAL_DOOR_OPEN: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/hFvphboowTEN1buUtIhxQA",
    SMALL_VERTICAL_DOOR_CLOSED: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/SwR0zwXETDyuajAqZuRFGZ",
    COMPUTER_LEFT_NORMAL: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FtqzAe3rkeOVC6PWi?alt=media&token=820eba3e-81ef-4925-abd6-aedee5c5dce5",
    COMPUTER_LEFT_HIGHLIGHTED: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FXqIJoV8oGjeC8DYn?alt=media&token=2967af19-9a9a-4eba-8b06-adf038416d61",
    COMPUTER_FRONT_NORMAL: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FzI6PXmZ9KQpyGzbY?alt=media&token=40df1631-2a82-4b28-b604-ec30ca9a4eeb",
    COMPUTER_FRONT_HIGHLIGHTED: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2Fya4oRWlCd2acQhZH?alt=media&token=f2512b2d-12a1-42ba-9dc6-b8f1046b303d",
    COMPUTER_RIGHT_NORMAL: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FCvQh1neJYUXUqZ30?alt=media&token=0f90c1f4-9bc3-45bb-9c6e-b8532527615f",
    COMPUTER_RIGHT_HIGHLIGHTED: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FNBPkTDOrD3XcymH8?alt=media&token=2287a3c2-9c33-4afe-8f76-61d5efaf0e37",
    COMPUTER_WALL_NORMAL: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/QN5EdwDj0X2ve3ydJAy6Ct",
    COMPUTER_WALL_HIGHLIGHTED: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/Q4EN69IJgXElpTag3IaGl2",
    WINDOW_DOWN_NORMAL: 'https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/cXdPtQvlXwRNgB9L9hufIK',
    WINDOW_DOWN_HIGHLIGHTED: 'https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/0GGdBGGIOUKg55knVE6Csk',
    WINDOW_UP_NORMAL: 'https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/kwyB7X2OVnwGXTAIn6PfYP',
    WINDOW_UP_HIGHLIGHTED: 'https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/Th6uDxRaeajkPNMLeLUjgv',
    WINDOW_HORIZONTAL_NORMAL: 'https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/iC2DLiAyR23qxOlS/fThB6dD4ypXVi378Paw3ab',
    PORTAL_NORMAL: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/internal-dashboard/images/5KXHBZX-f9edYGzcQfbyS",
    PORTAL_HIGHLIGHTED: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/internal-dashboard/images/Qq3rsFqweKch6eD2SIYHm",
    POSTER_2X2_NORMAL: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/soygFj00tz3XVhgreKUKw4",
    POSTER_2X2_HIGHLIGHTED: "https://cdn.gather.town/storage.googleapis.com/gather-town.appspot.com/uploads/72Qz2qF4X0Zn30Gt/V69MjVPGDmTfIcewYYgFc0",
    NOTE_NORMAL: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FZV64T7uzChV9N2Vi?alt=media&token=c6de8057-b19a-48b1-835b-78c25f08426e",
    NOTE_HIGHLIGHTED: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FqbDxtuJpAwjYl7ox?alt=media&token=bdc0ab0e-a632-489f-a8bd-c932c7264031",
    DOCUMENT_NORMAL: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2Fdx5P2y9bWZ4lEl9l?alt=media&token=bf39c8d7-91a0-4da4-933f-deb1f1579299",
    DOCUMENT_HIGHLIGHTED: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FoHjEonVChF23mjUL?alt=media&token=fbcc9fca-f4d4-42a1-8507-9a17f66032ee",
    LAPTOP_RIGHT_NORMAL: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2Fk4S7eqtITg6mvq5o?alt=media&token=e6034114-9439-4fed-a723-6851f21b9af0",
    LAPTOP_RIGHT_HIGHLIGHTED: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FQgcXblJfzy63QqGK?alt=media&token=59673a62-cee4-46ee-ac18-dc9fba81aa7d",
    LAPTOP_LEFT_NORMAL: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2F4EcXVu1D2v0oEWd4?alt=media&token=14b220f0-42da-418d-8b37-648fafbb3aa9",
    LAPTOP_LEFT_HIGHLIGHTED: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FTQONkhpUW82lLDjf?alt=media&token=ca5d83c4-9a75-41c3-bb84-0ef76da5bf37",
    POSTER_3X2_NORMAL_1: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FJLcO7fPfJlop9WvY?alt=media&token=29dbc584-d603-49cb-af86-028309197236",
    POSTER_3X2_NORMAL_2: "https://cdn.gather.town/v0/b/gather-town.appspot.com/o/internal-dashboard-upload%2FCkPsU5fuzIGGGaFi?alt=media&token=57cf71f2-e0d9-4196-8d1d-ddd79f63461f",
};

const externalUrls = {
    PROBLEM_1_GRAPH: "https://intranet.fluque.es/nextcloud/s/Kefmd2rD7q4ZRcC",
    PROBLEM_2_WINDOW_1: "https://intranet.fluque.es/nextcloud/s/xPHYnqbNPXH3cyA",
    PROBLEM_2_WINDOW_2: "https://intranet.fluque.es/nextcloud/s/PAjPQAMyqDCX883",
    PROBLEM_2_WINDOW_3: "https://intranet.fluque.es/nextcloud/s/7bCsMpGdtzwKtLr",
    PROBLEM_4_GRAPH: "https://intranet.fluque.es/nextcloud/s/jfBW9KQJ8P7GJo2",
    PROBLEM_4_FORMULAS_1: "https://intranet.fluque.es/nextcloud/s/NyMncX992mGaaq5",
    PROBLEM_4_FORMULAS_2: "https://intranet.fluque.es/nextcloud/s/DSFpcXQTxWiT3WF",
    PROBLEM_5_DOCUMENT_1: "https://intranet.fluque.es/nextcloud/s/PGtMYqfSa9yx8Xn",
    PROBLEM_5_DOCUMENT_2: "https://intranet.fluque.es/nextcloud/s/atcLsBsBjDjt53x",
    PROBLEM_5_DOCUMENT_3: "https://intranet.fluque.es/nextcloud/s/q5iSPjAqniz8boq"
}

export { objectUrls, externalUrls };
